services:
  api:
    container_name: BlessedApi
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./api
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /var/log/BlessedLogs/:/logs/
      - ../ssl:/app/ssl
    env_file:
      - ../.env
    networks:
      - db-network
    depends_on:
      - redis

  redis:
    container_name: BlessedRedis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - db-network



volumes:
  redis-data:

networks:
  db-network:
    external: true