services:
  web:
    container_name: reactSite
    build:
      context: ./
      dockerfile: Dockerfile
    command: nginx -g "daemon off;"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
