services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    name: db-network
